# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poEMirtbase_fit <- function(Y, N, alpha_init, beta_init, theta_init, unique_categories, a0, A0, b0, B0, constraint, std, maxit, verbose, tol, compute_ll) {
    .Call(`_poEMirt_poEMirtbase_fit`, Y, N, alpha_init, beta_init, theta_init, unique_categories, a0, A0, b0, B0, constraint, std, maxit, verbose, tol, compute_ll)
}

poEMirtbase_gibbs_fit <- function(Y, N, alpha, beta, theta, unique_categories, a0, A0, b0, B0, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose) {
    .Call(`_poEMirt_poEMirtbase_gibbs_fit`, Y, N, alpha, beta, theta, unique_categories, a0, A0, b0, B0, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose)
}

poEMirtdynamic_fit <- function(Y, N, alpha_init, beta_init, theta_init, unique_categories, timemap, timemap2, item_timemap, item_match, a0, A0, b0, B0, m0, C0, Delta, constraint, std, maxit, verbose, tol, compute_ll) {
    .Call(`_poEMirt_poEMirtdynamic_fit`, Y, N, alpha_init, beta_init, theta_init, unique_categories, timemap, timemap2, item_timemap, item_match, a0, A0, b0, B0, m0, C0, Delta, constraint, std, maxit, verbose, tol, compute_ll)
}

poEMirtdynamic_gibbs_fit <- function(Y, N, alpha, beta, theta, unique_categories, timemap, timemap2, item_timemap, item_match, a0, A0, b0, B0, m0, C0, Delta, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose) {
    .Call(`_poEMirt_poEMirtdynamic_gibbs_fit`, Y, N, alpha, beta, theta, unique_categories, timemap, timemap2, item_timemap, item_match, a0, A0, b0, B0, m0, C0, Delta, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose)
}

prediction <- function(N, alpha, beta, theta, unique_categories, item_timemap, model, type) {
    .Call(`_poEMirt_prediction`, N, alpha, beta, theta, unique_categories, item_timemap, model, type)
}

