# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poEMirtbase_fit <- function(Y, S, Nks, alpha_old, beta_old, theta_old, unique_categories, a0, A0, b0, B0, constraint, std, maxit, verbose, tol, compute_ll) {
    .Call(`_poEMirt_poEMirtbase_fit`, Y, S, Nks, alpha_old, beta_old, theta_old, unique_categories, a0, A0, b0, B0, constraint, std, maxit, verbose, tol, compute_ll)
}

poEMirtbase_gibbs_fit <- function(Y, S, Nks, alpha, beta, theta, unique_categories, a0, A0, b0, B0, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose) {
    .Call(`_poEMirt_poEMirtbase_gibbs_fit`, Y, S, Nks, alpha, beta, theta, unique_categories, a0, A0, b0, B0, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose)
}

poEMirtdynamic_fit <- function(Y, S, Nks, alpha_old, beta_old, theta_old, unique_categories, uJ_J, timemap2, item_timemap, IT, ITJ, a0, A0, b0, B0, m0, C0, Delta, constraint, alpha_fix, std, maxit, verbose, tol, compute_ll) {
    .Call(`_poEMirt_poEMirtdynamic_fit`, Y, S, Nks, alpha_old, beta_old, theta_old, unique_categories, uJ_J, timemap2, item_timemap, IT, ITJ, a0, A0, b0, B0, m0, C0, Delta, constraint, alpha_fix, std, maxit, verbose, tol, compute_ll)
}

poEMirtdynamic_gibbs_fit <- function(Y, S, Nks, sb_check, alpha, beta, theta, unique_categories, uJ_J, timemap2, item_timemap, IT, ITJ, a0, A0, b0, B0, m0, C0, Delta, alpha_fix, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose) {
    .Call(`_poEMirt_poEMirtdynamic_gibbs_fit`, Y, S, Nks, sb_check, alpha, beta, theta, unique_categories, uJ_J, timemap2, item_timemap, IT, ITJ, a0, A0, b0, B0, m0, C0, Delta, alpha_fix, PG_approx, constraint, std, iter, warmup, thin, save_item_parameters, verbose)
}

construct_sb_auxs <- function(Y, N, unique_categories) {
    .Call(`_poEMirt_construct_sb_auxs`, Y, N, unique_categories)
}

get_dynamic_info <- function(N, item_timemap, timemap) {
    .Call(`_poEMirt_get_dynamic_info`, N, item_timemap, timemap)
}

prediction <- function(N, alpha, beta, theta, unique_categories, item_timemap, model, type) {
    .Call(`_poEMirt_prediction`, N, alpha, beta, theta, unique_categories, item_timemap, model, type)
}

